# Generated by Django 5.2.8 on 2025-12-13 07:31

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('theme', models.CharField(default='vs-dark', max_length=50)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gists',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.CharField(default=api.models.generate_id, max_length=10, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_folder', models.BooleanField(default=False)),
                ('parent_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project')),
            ],
            options={
                'db_table': 'project_files',
                'indexes': [models.Index(fields=['project', 'parent_path'], name='project_fil_project_257d3f_idx')],
                'unique_together': {('project', 'path')},
            },
        ),
    ]
